# Generated by Django 3.1 on 2021-11-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20211108_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
